### ISSUE TITLE
AgoraChannelProfile has no member 'gameFreeMode'

### ISSUE THREAD

**Issue by ploverlake** [AgoraIO/Voice-Call-for-Mobile-Gaming#11]
error: type 'AgoraChannelProfile' has no member 'gameFreeMode'
error: type 'AgoraChannelProfile' has no member 'gameCommandMode'

**Comment by zhangtao1104** [comment]
which demo do you mean ?

**Comment by ploverlake** [comment]
> which demo do you mean ?

This one:
Voice-Call-for-Mobile-Gaming/Advanced-Voice-Call-for-Gaming/Spacewar-with-AMG-Voice-SDK-SpriteKit

I used that demo, and downloaded the latest SDK from the link in README, and the compiling errors occurred.

**Comment by zhangtao1104** [comment]
Please update the source code and download the sdk (http://download.agora.io/sdk/release/AMG_Voice_Native_iOS_HD_v2_2_17.zip?_ga=2.21743547.1629393472.1551064258-1899500272.1512557670) , Try again.

**Comment by ploverlake** [comment]
Thank you very much. There is no compiling errors at all.

**Comment by nsmith1024** [comment]
Im using Unity and want to do video broadcast from one to many. SetChannelProfile only has GAME_FREE_MODE and GAME_COMMAND_MODE which one do i use for broadcasting?

**Comment by zhangtao1104** [comment]
@nsmith1024  You can use GAME_COMMAND_MODE and use api named SetClientRole to control the role of the user.

**Comment by zhangtao1104** [comment]
This is our document.https://docs.agora.io/cn/Interactive%20Gaming/game_unity?platform=Unity

**Comment by nsmith1024** [comment]
Hello,

Thanks for your help, I set it like this on Unity, running on my Android phone device.

        mRtcEngine.SetChannelProfile(CHANNEL_PROFILE.GAME_COMMAND_MODE);
        mRtcEngine.SetClientRole(broadcast ? CLIENT_ROLE.BROADCASTER : CLIENT_ROLE.AUDIENCE);
and 
		mRtcEngine.OnJoinChannelSuccess = onJoinChannelSuccess;
		mRtcEngine.OnUserJoined = onUserJoined;
		mRtcEngine.OnUserOffline = onUserOffline;

When i run it, OnJoinChannelSuccess is called but OnUserJoined is not called. But as the broadcaster, i can see the video on the screen locally and im the only person on the channel. Is that the correct operation? OnUserJoined not being called?

Also the video frame rate is really low and jerky maybe its 10 frames per second (im seeing my local video feed on the screen) and the video is also upside down (I can probably fix the upside down easily by rotating the gameObject) but the low frame rate dont know how to fix.

**Comment by zhangtao1104** [comment]
Yes ,it is nomal, if you join channel success, the callback named OnJoinChannelSuccess will be called but not OnUserJoined , when the remote user of broadcaster join the same channel, the onUserJoined will be called.

**Comment by zhangtao1104** [comment]
The real video frame rate is 15. If you want to get a high frame rate, you can use the api named SetVideoProfile, but it will consume more cpu and memory.

**Comment by zhangtao1104** [comment]
If you want to control the camera, you can use the api named SwitchCamera.

**Comment by nsmith1024** [comment]
Hello, thanks for the response. 

1. Is the 15 fps because its broadcasting from the phone? what if i broadcast from the PC using something like OBS, will i get a better frame rate like 30fps?

2. the broadcaster doesnt want to see the other peoples screen, he just want to see his own feed as a preview and send that to others, so its just one to many, and no video in reverse.
