### ISSUE TITLE
Xcode 10.2 does not support building or migrating Swift 3.x target “AMGVoice”.

### ISSUE THREAD

**Issue by ploverlake** [AgoraIO/Voice-Call-for-Mobile-Gaming#14]
Hi there, when I use Xcode 10.2 to open the project 'Spacewar-with-AMG-Voice-SDK-SpriteKit', I got this error:

'''
Unsupported Swift Version

The target “AMGVoice” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.
'''

**Comment by zhangtao1104** [comment]
Please update the demo source code, and try again @ploverlake

**Comment by ploverlake** [comment]
Thank you very much, it works!
