### ISSUE TITLE
Room list

### ISSUE THREAD

**Issue by mustafacoskunn** [AgoraIO/Voice-Call-for-Mobile-Gaming#23]
How do I get all the rooms in a list?
I want others to join the room that is open with the "join" button?

**Comment by mustafacoskunn** [comment]
When it is an open room, I want them to join that room with their names. Would you show a sample code for this?

**Comment by plutoless** [comment]
hi you need to manage a room list yourself with your own server.

**Comment by mustafacoskunn** [comment]
I just want to see and see rooms that are open

**Comment by plutoless** [comment]
yes you need to manage it with your own server.
