### ISSUE TITLE
Oculus go volume control disappears after joining a channel

### ISSUE THREAD

**Issue by coccoalberto** [AgoraIO/Voice-Call-for-Mobile-Gaming#24]
Hi,
I made an application with Unity for Oculus go in which I have a 360 video, I can change the volume fine with the physical buttons of the device but when I join a room (mRtcEngine.JoinChannel) I can no longer change the volume of the video and the volume level indicator is not showing anymore, pressing the physical buttons only changes the voice chat volume, is there a way I can change the volume of both voice chat and video? 

When I press volume buttons unity logs this: 
`
D/UnityVolumeReceiver: OnReceive VOLUME_CHANGED_ACTION
D/UnityVolumeReceiver: skipping volume change from stream 0
`

**Comment by zhangtao1104** [comment]
The reason why you can only adjust the voice call volume by physical button is that the default audio route of real time voice call is Call, but the audio route of oculus is media. 
So you can only adjust the voice call.

**Comment by zhangtao1104** [comment]
You can switch the audio route of the voice call to meida by the api named SetAudioProfile.
 mRtcEngine.SetAudioProfile(AUDIO_PROFILE_TYPE.AUDIO_PROFILE_DEFAULT, AUDIO_SCENARIO_TYPE.AUDIO_SCENARIO_GAME_STREAMING);

**Comment by coccoalberto** [comment]
> You can switch the audio route of the voice call to meida by the api named SetAudioProfile.
> mRtcEngine.SetAudioProfile(AUDIO_PROFILE_TYPE.AUDIO_PROFILE_DEFAULT, AUDIO_SCENARIO_TYPE.AUDIO_SCENARIO_GAME_STREAMING);

Thank you,
this solved the issue
