### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by daxini** [AgoraIO/Voice-Call-for-Mobile-Gaming#7]
I got the SDK from http://download.agora.io/sdk/release/AMG_Voice_Unity3D_HD_v2_1.zip and followed the instructions to replace the android, ios and scripts files and I get the following error...

I get this error both for "Voice-Call-for-Mobile-Gaming/Advanced-Voice-Call-for-Gaming/Spacewar-with-AMG-Voice-SDK-Unity/" as well as "Video-Call-for-Mobile-Gaming/Hello-Video-Unity-Agora/"

CommandInvokationFailure: Gradle build failed.
/home/scd/Unity/Hub/Editor/2018.3.0f2/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/Linux/bin/java -classpath "/home/scd/Unity/Hub/Editor/2018.3.0f2/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

Where:
Build file '/home/scd/Source/unity/Voice-Call-for-Mobile-Gaming-master/Advanced-Voice-Call-for-Gaming/Spacewar-with-AMG-Voice-SDK-Unity/Temp/gradleOut/build.gradle' line: 17

What went wrong:
A problem occurred evaluating root project 'gradleOut'.

Failed to apply plugin [id 'com.android.application']
Gradle version 2.10 is required. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in /home/scd/Source/unity/Voice-Call-for-Mobile-Gaming-master/Advanced-Voice-Call-for-Gaming/Spacewar-with-AMG-Voice-SDK-Unity/Temp/gradleOut/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 0s
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action1 progress, System.String error) UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by zhangtao1104** [comment]
I have the following three methods to suggest that customers try to modify:

1: The customer creates an empty project in his own environment, then compiles the project selection gradle and selects Export Project. After the project is successfully exported, view the build.gradle in the exported Android Project. Check the default gradle version number of Unity. What, this gradle version is the gradle version of the client's local environment, then modify the version number in mainTemplate.gradle to the version number obtained above, and then try to succeed.

2: If there is only one Plugin in the client project, you can delete mainTemplate.gradle and then directly select gradle to compile the project and let Unity build its own gradle.

 

3: If you don't delete mainTemplate.gradle, you can choose it in Unity Build

    Build Settings->Build System (Gradle)->Export Project,

After exporting the Android project, open the project with Android Studio and modify the gradle version in build.gradle. The modified gradle version number refers to the gradle version of the native Android Studio environment. View the local gradle version of Android Studio in my local path:

/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle

This path needs to be determined based on the customer's actual environment.

Then you can compile the APK.

**Comment by JanisSharma** [comment]
You need to change File > Settings > Builds,Execution,Deployment > Build Tools > Gradle >Gradle home path

On Mac OS, change the path in Android Studio > Preferences > Builds,Execution,Deployment > Build Tools > Gradle >Gradle home

Or set Use default gradle wrapper and edit Projectgradlewrappergradle-wrapper.properties files field distributionUrl like this

distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip

Full Source Code At [Here](https://icetutor.com/question/gradle-version-2-10-is-required-error)
