### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by NVentimiglia** [AgoraIO/Voice-Call-for-Mobile-Gaming#9]
Looking into this SDK, I am completely lost.

- No documentation
- What are these 'PLACEHOLDER' files ?
- Sample scene is missing scripts
- Please Advise how to use this thing

**Comment by plutoless** [comment]
hi @NVentimiglia  sorry for the bad use experience. could you pls help identify which sample you are having difficult with? Is it within Basic-Video-Call-For-Gaming or Advanced one? And which platform?

**Comment by NVentimiglia** [comment]
https://github.com/AgoraIO/Voice-Call-for-Mobile-Gaming/tree/master/Basic-Voice-Call-for-Gaming/Hello-Unity3D-Agora

This one, when I copied over the plugins, things did not rebind.
Maybe we can use unity packages here ?

**Comment by zhangtao1104** [comment]
First, create a developer account at Agora.io, and obtain an App ID. Update "HelloUnity3D.cs" with your App ID.

private static string appId = "YOUR APP ID";
Next, download the Agora Gaming SDK from Agora.io SDK. Unzip the downloaded SDK package and

copy files from libs/Android/ in SDK to Assets/Plugins/Android/AgoraAudioKit.plugin/libs/ in project
copy files from libs/iOS/ in SDK to Assets/Plugins/iOS/ in project
copy files from libs/Scripts/AgoraGamingSDK/ in SDK to Assets/Scripts/AgoraGamingSDK/ in project
Finally, Open project with Unity and run.

Did you run demo according to the README ? @NVentimiglia

**Comment by NVentimiglia** [comment]
@zhangtao1104 the issue is with the scene / script metadata bindings. The prefabs scripts 'are missing'

**Comment by zhangtao1104** [comment]
1: Scripts in sdk don't need to be bound to any prefabs. So I do not know what you mean  " The prefabs scripts 'are missing'  ". I can run it easily.

2: There is another the same demo in sdk package that you do not need to copy anything (The sdk plugin is already copied.). You can try that demo. It is in samples/Hello-Unity3D-Agora. You only need to update "HelloUnity3D.cs" with your App ID.

**Comment by zhangtao1104** [comment]
Is there still any question? @NVentimiglia

**Comment by NVentimiglia** [comment]
Scripts attached to game objects in this file are missing.
https://github.com/AgoraIO/Voice-Call-for-Mobile-Gaming/blob/master/Basic-Voice-Call-for-Gaming/Hello-Unity3D-Agora/Assets/HelloUnity3D.unity

**Comment by zhangtao1104** [comment]
Which unity version do you use? And which platform do you use (macos or others)?

**Comment by nsmith1024** [comment]
Im using the unity example, im wondering why would someone use the same script in two different scenes (in the demo)? It makes everything more confusing because you dont know which instance is being used, i want to attach something to the script, but it gets switched out when the scene is changed since the same script is in the other scene too, so that cant work. Cant seem to understand why two scenes are needed in the demo when all its doing is joining, its like processing the video connection using two scenes makes it more confusing to understand.
